차트50 = [
'새삥 (Prod. ZICO) (Feat. 호미들)',  
"After LIKE",				
"Hype boy",		
"Shut Down",			
"Attention",			
"Pink Venom",			
"Rush Hour (Feat. j-hope of BTS)",	
"LOVE DIVE",			
"딱 10CM만",			
"Monologue",			
"그때 그 순간 그대로 (그그그)",		
"Cookie",				
"그라데이션",			
"자격지심 (Feat. ZICO)",		
"우린 그렇게 사랑해서",		
"보고싶었어",			
"FOREVER 1",			
"사랑인가 봐",			
"정이라고 하자 (Feat. 10CM)",		
"TOMBOY",				
"내가 아니라도",			
"LAW (Prod. Czaer)",			
"해요 (2022)",	
"나의 X에게",		
"사랑은 늘 도망가",			
"SNEAKERS",			
"내 기쁨은 너가 벤틀리를 끄는 거야",	
"ELEVEN",				
"That's Hilarious",			
"That That (prod. & feat. SUGA of BTS)",	
"FEARLESS",			
"취중고백",				
"너의 모든 순간",			
"LOVE me",				
"POP!"	,			
"I Don't Think That I Like Her",		
"Love story"	,		
"다정히 내 이름을 부르면"	,	
"우리들의 블루스"		,	
"도깨비불 (Illusion)"		,	
"봄여름가을겨울 (Still Life)"		,
"사랑한다고 말해줘"	,		
"위 새벽에 걸려온 너의 전화는",		
"STAY"		,	
"통화연결음",			
"스티커 사진"	,		
"모든 날, 모든 순간 (Every day, Every Moment)",
"신호등"	,		
"다시 만날 수 있을까",		
"밤하늘의 별을(2020)"]
차트50가수 = ["지코 (ZICO)",
"IVE (아이브)",
"NewJeans",
"BLACKPINK",
"NewJeans",
"BLACKPINK",
"Crush",
"IVE (아이브)",
"10CM, BIG Naughty (서동현)",
"테이",
"WSG워너비 (가야G)",
"NewJeans",
"10CM",
"BE'O (비오)",
"강민경 (다비치), 잔나비 최정훈",
"WSG워너비 (4FIRE)",
"소녀시대 (GIRLS' GENERATION)",
"멜로망스",
"BIG Naughty (서동현)",
"(여자)아이들",
"주호",
"윤미래, 비비 (BIBI)",
"#안녕",
"경서",
"임영웅",
"ITZY (있지)",
"김승민",
"IVE (아이브)",
"Charlie Puth",
"싸이 (PSY)",
"LE SSERAFIM (르세라핌)",
"김민석 (멜로망스)",
"성시경",
"BE'O (비오)",
"나연 (TWICE)",
"Charlie Puth",
"볼빨간사춘기",
"경서예지, 전건호",
"임영웅",
"aespa",
"BIGBANG (빅뱅)",
"탑현",
"한동근",
"The Kid LAROI, Justin Bieber",
"보라미유, MJ (써니사이드)",
"21학번",
"폴킴",
"이무진",
"임영웅",
"경서"]
발라드 = [
"그때 그 순간 그대로 (그그그)",
"Monologue ",
"우린 그렇게 사랑해서 ",
"사랑인가 봐 (사내맞선 OST 스페셜 트랙) ",
"내가 아니라도 ",
"나의 X에게",
"해요 (2022)",
"사랑은 늘 도망가",
"취중고백",
"너의 모든 순간",
"다정히 내 이름을 부르면",
"우리들의 블루스",
"사랑한다고 말해줘",
"새벽에 걸려온 너의 전화는",
"통화연결음",
"모든 날, 모든 순간 (Every day, Every Moment)",
"스티커 사진",
"밤하늘의 별을(2020)",
"다시 만날 수 있을까",
"드라마",
"내 손을 잡아",
"바보에게 바보가 (웹툰 '연애의 발견' X 이석훈)",
"늦은 밤 헤어지긴 너무 아쉬워",
"듣고 싶을까",
"고백하는 취한밤에 (Prod. 2soo)",
"바라만 본다",
"아버지",
"언제나 사랑해",
"어떻게 이별까지 사랑하겠어, 널 사랑하는 거지",
"인생찬가",
"팡파레",
"가을 타나 봐",
"못해",
"미친 것처럼",
"취기를 빌려 (취향저격 그녀 X 산들)",
"고백",
"가을 안부",
"광화문에서 (At Gwanghwamun)",
"그 하루(feat.반하나)",
"희재",
"밤편지",
"가을밤 떠난 너",
"이러면 안 될 거 아는데 너 앞에만 서면 나락 (Feat. 10CM)",
"너를 만나",
"거리에서",
"사랑이야",
"그중에 그대를 만나",
"늦은 밤 너의 집 앞 골목길에서",
"11:11",
"아이와 나의 바다"
]
발라드가수 = ["WSG워너비 (가야G)",
"테이",
"강민경 (다비치), 잔나비 최정훈",
"멜로망스",
"주호",
"경서",
"#안녕",
"임영웅",
"김민석 (멜로망스)",
"성시경",
"경서예지, 전건호",
"임영웅",
"탑현",
"한동근",
"보라미유, MJ (써니사이드)",
"폴킴",
"21학번",
"경서",
"임영웅",
"아이유",
"아이유",
"이석훈",
"케이시 (Kassy)",
"MSG워너비(M.O.M)",
"임재현",
"MSG워너비(M.O.M)",
"임영웅",
"케이시 (Kassy)",
"AKMU (악뮤)",
"임영웅",
"다비치",
"바이브",
"김나영",
"V.O.S",
"산들",
"멜로망스",
"먼데이 키즈 (Monday Kiz)",
"규현 (KYUHYUN)",
"주호",
"성시경",
"아이유",
"케이시 (Kassy)",
"딘딘 (DINDIN)",
"폴킴",
"성시경",
"케이시 (Kassy)",
"김호중",
"노을",
"태연 (TAEYEON)",
"아이유"
]
힙합 = [
"새삥 (Prod. ZICO) (Feat. 호미들)",
"Shut Down",
"Pink Venom",
"자격지심 (Feat. ZICO)",
"LAW (Prod. Czaer)",
"내 기쁨은 너가 벤틀리를 끄는 거야",
"회전목마 (Feat. Zion.T, 원슈타인) (Prod. Slom)",
"MY BAG",
"OHAYO MY NIGHT",
"잠수이별 (Prod. 코드 쿤스트)",
"리무진 (Feat. MINO) (Prod. GRAY)",
"사이렌 Remix (Feat. UNEDUCATED KID, Paul Blanco)",	
"Counting Stars (Feat. Beenzino)",
"Summer (Feat. BE’O (비오))",
"METEOR",
"Rainy day (Feat. ASH ISLAND, Skinny Brown)",
"만남은 쉽고 이별은 어려워 (Feat. Leellamarz) (Prod. TOIL)",
"Trip (Feat. Hannah)",
"멜로디",
"시차 (We Are) (Feat. 로꼬 & GRAY)",
"아무노래",
"Don't go(feat. ASH ISLAND)",
"Never Grind",
"Kitty(Feat.미연(여자(아이들)))",
"낭만교향곡(Feat. CHANGMO, 박재범)",
"Paranoid",
"GENIUS (Feat. CHANGMO)",
"Rush Hour (Feat. j-hope of BTS)",
"NO THANXXX",
"High (Feat. PENOMECO)",
"Till I Die",
"GOTT(Feat. MOON & Woo & Jvcki Wai)",
"PNM",
"Teeenage in Closet",
"Wang Like Alexander",
"SUPERBEEWHY (Prod. by BeewhY)",
"MAGMA (Prod. by BewhY)",
"Can't Stop This Party",
"ON AIR (Feat. Loco, Jay Park & GRAY)",
"Joker",
"Wayne Remix (Feat. G2, Huckleberry P & P-type)",
"One of Them (Feat. JUSTHIS, EK)",
"Golden Mulan",
"business boy (Feat.nongmill kim, BLOO)",
"The Time Goes On",
"Acroabat 곡예사",
"한국",
"털어! (Feat. M1NU, Veinyfl, Swervy, 래원, 이영지, Lil Nekh, D.Ark)",
"Selfmade Orange",
"호심술 (Love peace)"
]
힙합가수 = [
"지코 (ZICO)",
"BLACKPINK",
"BLACKPINK",
"BE'O (비오)",
"윤미래, 비비 (BIBI)",
"김승민",
"sokodomo",
"(여자)아이들",
"디핵 (D-Hack), PATEKO (파테코)",
"우원재, meenoi (미노이)",
"BE'O (비오)",
"호미들",
"BE'O (비오)",
"Paul Blanco",
"창모 (CHANGMO)",
"PATEKO (파테코)",
"베이식 (Basick)",
"릴러말즈 (Leellamarz)",
"ASH ISLAND",
"우원재",
"지코 (ZICO)",
"CHANMINA, ASH ISLAND",
"Chillin Boi G, 100KGOLD, HOWLER",
"키드밀리 (Kid Milli), dress",
"서동현",
"ASH ISLAND",
"D.Ark",
"Crush",
"에픽하이, MINO, 사이먼 도미닉, THE Quiett",
"이바다,페노메코",
"페노메코",
"사이먼 도미닉",
"페노메코",
"Hash Swan",
"Hash Swan",
"수퍼비",
"펀치넬로, 행주, BewhY",
"서리",
"릴보이",
"서동현",
"허클베리 피, 피타입",
"허클베피 피, 저스디스, EK",
"Lil cherry,GOLDBUUDA",
"허성현",
"BeewhY",
"조광일",
"조광일",
"서동현",
"창모, 수퍼비",
"타이거JK"
]
노래방_인기가요 = [
'DrunKen Confession',
'호랑수월가',
'사랑은 늘 도망가',
'추억은 만남보다 이별에 남아',
'좋니',
'Limousine (Feat.MINO)',
'회전목마',
'체념',
'Only You',
'응급실',
'Serenade',
'ELEVEN',
'어디에도',
'까만 안경',
'밝게 빝나는 별이 되어 비춰줄게',
'Timeless',
'오래된 노래',
'Foolish Love',
'Dial Your Number',
'Counting stars(Feat. Beenzino)',
'힘든 건 사랑이 아니다',
'seomyun',
'Savage',
'VVS (Feat.JUSTHIS)',
'꿈속에서 너 ',
'한잔이면 지워질까',
'Sunddenly',
'Next Level',
'포장마차',
'LOVE DAY(2021)(바른연애 길잡이 X 양요섭, 정은지)',
'소주 한잔',
'Crazy Excuse',
'취했나봐',
'사이렌 Remix (Feat. UNDUCATED KID, Paul Blanco)',
'Aloha',
'곡예사',
'One Love',
'서툰 이별을 하려해',
'첫눈처럼 너에게 가겠다',
'Lonely night',
'Marry Me',
'Freak (Prod.Slom)',
'신촌을 못가 (소울충만 체키라웃)',
'지나오다',
'이별주',
'모든 날, 모든 순간',
'그대 없는 밤에',
'To You My Light (feat. Lee Raon)',
'눈의 꽃',
'다정히 내 이름을 부르면']
노래방_인기가요가수 = [
'김민석',
'탑현',
'임영웅',
'정동하',
'윤종신',
"BE'O, MINO",
'sokodomo, Zion.T, 원슈타인',
'빅마마',
'정상동기',
'lzi',
'JEON WOO SUNG',
'IVE',
'엠씨더맥스',
'이루',
'송이한',
'SG 워너비',
'스탠딩 에그',
'M.O.M',
'An Nyeong',
"BE'O, 빈지노",
'임창정',
'순순희',
'aespa',
'미란이, 먼치맨, Khundi Panda, 머쉬베놈',
'에이치코드, 전상근',
'황인욱',
"BE'O",
'aespa',
'황인욱',
'양요섭, 정은지',
'임창정',
'이예준',
'황인욱',
'호미들',
'조성석',
'조광일',
'엠씨더맥스',
'윤토벤, 전상근',
'에일리',
'벤',
'마크툽',
'릴보이, 원슈타인, Chillin Homie, 스카이민혁',
'김진우',
'닐로',
'황인욱',
'폴킴',
'에이치코드, 전상근',
'마크툽, Leeraon',
'박효신',
'경서예지',
]
팝송 = [
'That’s Hilarious',
'I Don’t Think That I Like Her',
'STAY',
'Left and Right(Feat. Jung Kook of BTS)',
'Off My Face',
'I Ain’t Worried',
'Dangerously',
'My Universe',
'I’m Not The Only One',
'Loving You Girl(Feat. Hkeem)',
'Bad',
'Bad Habits',
'2002',
'12:45(Stripped)',
'One Call Away',
'GHOST TOWN',
'Light Switch',
'abcdefu',
'Every Second',
'Snowman',
'Paris in The Rain',
'Love Yourself',
'Peaches(Feat. Daniel Caesar & Giveon)',
'YOUTH',
'bad guy',
'Memories',
'Attention',
'INDUSTRY BABY',
'Stuck with U',
'parachute',
'Shape of You',
'When I Get Old',
'As It Was',
'comethru',
'Lost Stars',
'Maniac',
'Tiny Riot',
'World’s Smallest Violin',
'Unholy',
'Bad Decisions',
'Like Strangers Do',
'See You Again',
'Stronger(What Doesn’t Kill You)',
'Dance Monkey',
'Never Not',
'Sugar',
'We Don’t Talk Anymore(Feat. Selena Gomez)',
'Believer',
'Someone Like You',
'At My Worst',
'Charlie Be Quiet!'
]
팝송가수= [
'Charlie Puth',
'Charlie Puth',
'The Kid LAROI, Justin Bieber',
'Charlie Puth',
'Justin Bieber',
"I Ain't Worried (From “Top Gun: Maverick”)",
'Charlie Puth',
'Coldplay X BTS',
'Sam Smith',
'Peder Elias',
'Christopher',
'Ed Sheeran',
'Anne-Marie',
'Etham',
'Charlie Puth',
'Benson Boone',
'Charlie Puth',
'GAYLE',
'Mina Okabe',
'Sia',
'Lauv',
'BTS',
'Justin Bieber',
'Troye Sivan',
'Billie Eilish ',
'Maroon 5',
'NewJeans',
'Lil Nas X, Jack Harlow',
'Ariana Grande & Justin Bieber',
'John K',
'Ed Sheeran',
'Christopher x CHUNG HA',
'Harry Styles',
'Jeremy Zucker',
'Adam Levine',
'Stray Kids',
'Sam Ryder',
'AJR',
'Sam Smith',
'BTS & Snoop Dogg',
'AJ Mitchell',
'Wiz Khalifa',
'Kelly Clarkson',
'TONES AND I',
'Lauv',
'Maroon5',
'Charile Puth',
'Imagine Dragons',
'Adele',
'Pink Sweat',
'Charile Puth'
]

from 플레이리스트 import 플레이리스트_메뉴
from 좋아요 import 좋아요_메뉴
from 장르 import 장르_메뉴
from 유틸 import *

playlist=[]
heartlist=[]
music_list=[차트50,발라드,힙합,노래방_인기가요,팝송]
singer_list=[차트50가수,발라드가수,힙합가수,노래방_인기가요가수,팝송가수]

def 메인화면():
    while 1:
        print('[ 메인화면 ]')
        print('1. 플레이리스트 메뉴')
        print('2. 좋아요 메뉴')
        print('3. 장르 메뉴')
        print('4. 프로그램 종료')
        com=int(input('실행 번호: '))
        if com==1:
            구분선()
            플레이리스트_메뉴(music_list,singer_list,playlist,heartlist)
        elif com==2:
            구분선()
            좋아요_메뉴(music_list,singer_list,playlist,heartlist)
        elif com==3:
            구분선()
            장르_메뉴(music_list,singer_list,playlist,heartlist)
        elif com==4:
            구분선()
            print('프로그램을 종료합니다.')
            구분선()
            break
        else:
            다시입력()

메인화면()